In [1]:
import numpy as np
from my_logistic_regression import MyLogisticRegression as MyLR

In [2]:
X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [3., 5., 9., 14.]])
Y = np.array([[1], [0], [1]])
mylr = MyLR([2, 0.5, 7.1, -4.3, 2.09])

In [8]:
mylr.predict_(X)

[[ 1.  1.  2.  3.]
 [ 5.  8. 13. 21.]
 [ 3.  5.  9. 14.]]


In [4]:
mylr.loss_(X,Y)

11.513423954053735

In [5]:
mylr.fit_(X, Y)
mylr.theta

array([[ 2.11826435],
       [ 0.10154334],
       [ 6.43942899],
       [-5.10817488],
       [ 0.6212541 ]])

In [6]:
mylr.predict_(X)

array([[0.57606717],
       [0.68599807],
       [0.06562156]])

In [7]:
mylr.loss_(X, Y)

1.4779126923052281